name: Run MLFlow Project

on:
  push:
    branches: [main]

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        auto-update-conda: true
        activate-environment: ""
        python-version: "3.9"

    - name: Set MLFLOW_CONDA_HOME
      run: echo "MLFLOW_CONDA_HOME=$(dirname $(dirname $(which conda)))" >> $GITHUB_ENV

    - name: Install MLflow
      run: pip install mlflow

    - name: Run MLflow Project
      run: |
        mlflow run . --env-manager=conda
