name: Retrain Crop Model on Push

on:
  push:
    paths:
      - 'MLProject/**'
      - '.github/workflows/mlflow_retrain.yml'

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Conda
      uses: conda-incubator/setup-miniconda@v2
      with:
        auto-activate-base: false
        python-version: 3.9

    - name: Create Conda Env
      run: |
        conda env create -f MLProject/conda.yaml
        source ~/miniconda3/etc/profile.d/conda.sh
        conda activate crop-env

        # Jalankan MLflow Project
        cd MLProject
        mlflow run .
