name: MLflow CI Pipeline

on:
  push:
    branches: [ main ]

jobs:
  run-mlflow:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        activate-environment: mlflow-env
        python-version: 3.9
        auto-activate-base: false

    - name: Install dependencies
      run: |
        conda install -n mlflow-env pip -y
        conda run -n mlflow-env pip install mlflow scikit-learn pandas

    - name: Run MLflow project
      run: |
        conda run -n mlflow-env mlflow run ./MLProject --env-manager=conda --experiment-name "CI Run"

    - name: Upload artifacts (to GitHub)
      uses: actions/upload-artifact@v4
      with:
        name: model-artifacts
        path: /home/runner/.mlflow/artifacts  # sesuaikan jika disimpan di lokasi lain

  build-docker:
    needs: run-mlflow
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Install MLflow
      run: |
        pip install mlflow

    - name: Build Docker Image
      run: |
        mlflow build-docker -n crop-recommendation-image -f MLProject

    - name: Log in to Docker Hub
      run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

    - name: Push Docker Image
      run: |
        docker tag crop-recommendation-image ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-image:latest
        docker push ${{ secrets.DOCKER_USERNAME }}/crop-recommendation-image:latest
