name: Run MLflow with Conda

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  mlflow-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Miniconda
      uses: conda-incubator/setup-miniconda@v3
      with:
        python-version: 3.9
        activate-environment: mlflow-env
        environment-file: MLProject/conda.yaml
        auto-update-conda: true
        auto-activate-base: false
        conda-solver: libmamba

    - name: Install MLflow
      shell: bash -l {0} 
      run: |
        conda activate mlflow-env
        pip install mlflow

    - name: Run MLflow Project
      shell: bash -l {0}  
      run: |
        conda activate mlflow-env
        mlflow run ./MLProject --env-manager=local
        mlflow run ./MLProject --env-manager=local
